server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: kafka-logs
    kafka:
      brokers:
        - "kafka:9092"
      topics:
        - "logs-topic"
      group: "promtail-group"
      start_offset: "oldest"
    relabel_configs:
      - source_labels: [__topic__]
        target_label: job
      - source_labels: [level]
        target_label: level
      - source_labels: [component]
        target_label: component
